databases:
  - name: helpjuice
    databaseName: helpjuice_production
    user: emmanuel

services:
  - type: web
    name: helpjuice
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helpjoice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
